#########################################################################
app:
  label: petclinic
  image: dsyer/petclinic
  replicaCount: 2
  containerPort: 8080

  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  configMap:
    name: petclinic-config
    data:
      SPRING_PROFILES_ACTIVE: "postgres"
      SERVICE_BINDING_ROOT: "/bindings"
      SPRING_APPLICATION_JSON: |
        {
          "management.endpoint.health.probes.add-additional-paths": true,
          "spring.datasource.url": "jdbc:postgresql://demo-db-postgresql:5432/petclinic"
        }

  bindings:
    enabled: true
    mountPath: /bindings/secret
    secretName: db-secrets

#########################################################################
# Bitnami PostgreSQL instead of custom DB
postgresql:
  enabled: true
  fullnameOverride: demo-db

  auth:
    # password is NOT specified here, taken from `db-secrets` secret
    existingSecret: db-secrets  # Secret injected via SealedSecrets
    username: user
    database: petclinic

  primary:
    persistence:
      enabled: true
      storageClass: standard
      size: 1Gi

#########################################################################
service:
  app:
    name: petclinic-service
    port: 80
    targetPort: 8080

#########################################################################
ingress:
  enabled: true
  name: petclinic-ingress
  host: petclinic.local
  serviceName: petclinic-service
  servicePort: 80
