###################################################
# Deployments & Statefulsets (APP & DB)
# appName: petclinic

appLabel: petclinic
appReplicaCount: 2

dbLabel: demo-db
dbReplicaCount: 1



appImageName: dsyer/petclinic
# appImageVersion: latest
appContainerPort: 8080

dbImageName: postgres
dbImageVersion: 17

dbContainerPort: 5432

###################################################
# Services
appService:
  name: petclinic-service
  ports:
    port: 80
    targetPort: 8080

dbService:
  name: demo-db
  ports:
    port: 5432

###################################################
# Ingress 
ingress:
  name: petclinic-ingress
  rules:
    host: petclinic.local
    appServiceName: petclinic-service
    appServicePort: 80

###################################################
# Configmaps 
appConfigMap:
  name: petclinic-conf

# Secrets
postgresqlSecret:
  name: db-secrets