apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appService.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.appService.ports.port }}
      targetPort: {{ .Values.appService.ports.targetPort }}
  selector:
    app: {{ .Values.appLabel }}