apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.app.name }}
spec:
  selector:
    app: {{ .Values.app.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.app.port }}
      targetPort: {{ .Values.service.app.targetPort }}
