apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.db.name }}
spec:
  ports:
    - port: {{ .Values.service.db.port }}
      targetPort: {{ .Values.db.containerPort }}
  selector:
    app: {{ .Values.db.label }}
  clusterIP: None
