apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.dbLabel }}
  labels:
    app: {{ .Values.dbLabel }}
spec:
  serviceName: {{ .Values.dbLabel }}
  replicas: {{ .Values.dbReplicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.dbLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.dbLabel }}
    spec:
      containers:
        - image: "{{ .Values.dbImageName }}:{{ .Values.dbImageVersion }}"
          name: postgresql
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresqlSecret.name }}
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresqlSecret.name }}
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresqlSecret.name }}
                  key: database
          ports:
            - containerPort: {{ .Values.dbContainerPort }}
              name: postgresql
          livenessProbe:
            tcpSocket:
              port: postgresql
          readinessProbe:
            tcpSocket:
              port: postgresql
          startupProbe:
            tcpSocket:
              port: postgresql
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi
