apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.label }}-deployment
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.label }}
    spec:
      containers:
        - name: {{ .Values.app.label }}-container
          image: "{{ .Values.app.image }}"
          envFrom:
            - configMapRef:
                name: {{ .Values.app.configMap.name }}
          ports:
            - name: http
              containerPort: {{ .Values.app.containerPort }}
          # resources:
          #   requests:
          #     cpu: {{ .Values.app.resources.requests.cpu | quote }}
          #     memory: {{ .Values.app.resources.requests.memory | quote }}
          #   limits:
          #     cpu: {{ .Values.app.resources.limits.cpu | quote }}
          #     memory: {{ .Values.app.resources.limits.memory | quote }}
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          startupProbe:
            tcpSocket:
              port: http
          {{- if .Values.app.bindings.enabled }}
          volumeMounts:
            - mountPath: {{ .Values.app.bindings.mountPath }}
              name: binding
              readOnly: true
          {{- end }}
      {{- if .Values.app.bindings.enabled }}
      volumes:
        - name: binding
          projected:
            sources:
              - secret:
                  name: {{ .Values.app.bindings.secretName }}
      {{- end }}
