apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appLabel }}-deployment
spec:
  replicas: {{ .Values.appReplicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      containers:
        - name: {{ .Values.appLabel }}-container
          image: {{ .Values.appImageName }}
          envFrom:
            - configMapRef:
                name: {{ .Values.appConfigMap.name }}
          ports:
            - name: http
              containerPort: {{ .Values.appContainerPort }}
          livenessProbe:
            httpGet:
              path: /livez
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          volumeMounts:
            - mountPath: /bindings/secret
              name: binding
              readOnly: true
      volumes:
        - name: binding
          projected:
            sources:
              - secret:
                  name: {{ .Values.postgresqlSecret.name }}
