apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
spec:
  rules:
    - host: {{ .Values.ingress.rules.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.rules.appServiceName}}
                port:
                  number: {{ .Values.ingress.rules.appServicePort }}
